import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" style={{ width: "100%" }}>
      <body style={{ width: "100%", margin: 0, padding: 0 }}>{children}</body>
    </html>
  );
}
